# Generated by Django 3.0 on 2019-12-22 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=256)),
                ('resistance', models.CharField(choices=[('BB', 'Barbell'), ('BW', 'Body weight'), ('CB', 'Curl bar'), ('DB', 'Dumbbell')], max_length=2)),
            ],
        ),
    ]
